//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2023. 04. 26. 2:07:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Filmadatbazis
{
    public partial class enActor {

        public enActor()
        {
            this.enMovie_Casts = new List<enMovie_Cast>();
            OnCreated();
        }

        public int act_id { get; set; }

        public string act_fname { get; set; }

        public string act_lname { get; set; }

        public string act_gender { get; set; }

        public virtual IList<enMovie_Cast> enMovie_Casts { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
