//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2023. 04. 26. 2:07:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Filmadatbazis
{
    public partial class enRating {

        public enRating()
        {
            OnCreated();
        }

        public int id { get; set; }

        public int mov_id { get; set; }

        public int rev_id { get; set; }

        public int rev_stars { get; set; }

        public int num_o_ratings { get; set; }

        public virtual enReviewer enReviewer { get; set; }

        public virtual enMovie enMovie { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
