//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2023. 04. 26. 2:07:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Filmadatbazis
{
    public partial class enMovie {

        public enMovie()
        {
            this.enMovie_Casts = new List<enMovie_Cast>();
            this.enMovie_Directions = new List<enMovie_Direction>();
            this.enMovie_Genres = new List<enMovie_Genres>();
            this.enRatings = new List<enRating>();
            this.enMovie_Streamings = new List<enMovie_Streaming>();
            OnCreated();
        }

        public int mov_id { get; set; }

        public string mov_title { get; set; }

        public string mov_description { get; set; }

        public int move_year { get; set; }

        public int mov_time { get; set; }

        public string mov_lang { get; set; }

        public DateTime mov_dt_rel { get; set; }

        public string mov_rel_country { get; set; }

        public string mov_trailer { get; set; }

        public string mov_pic { get; set; }

        public virtual IList<enMovie_Cast> enMovie_Casts { get; set; }

        public virtual IList<enMovie_Direction> enMovie_Directions { get; set; }

        public virtual IList<enMovie_Genres> enMovie_Genres { get; set; }

        public virtual IList<enRating> enRatings { get; set; }

        public virtual IList<enMovie_Streaming> enMovie_Streamings { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
